// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Link struct {
	ID          int64       `json:"id"`
	OriginalUrl string      `json:"original_url"`
	ShortName   string      `json:"short_name"`
	ShortUrl    string      `json:"short_url"`
	CreatedAt   interface{} `json:"created_at"`
}
